POST http://localhost:8080/emails/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Thaneat",
    "lastName": "Saithong",
    "email": "nest@example.com"
}

###

POST http://localhost:8080/campaigns/prepare HTTP/1.1
Content-Type: application/json

{
    "subject": "[TEST] LINE MAN Delivery Promotion 500 THB",
    "bodyTemplate": "Hi {{firstName}} {{lastName}}\\n\\n Pleases use coupon code LM500FREE within 31 April."
}

###
# Response
# {"id": "something"}

POST http://localhost:8080/campaigns/launch HTTP/1.1
Content-Type: application/json

{
    "id": "something"
}